name: zenbreak
description: A cross-platform desktop wellness app.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  tray_manager: ^0.2.0
  window_manager: ^0.3.0
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.0
  vibration: ^1.7.5
  audioplayers: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/sounds/notification.wav
